export type CapstoneOption = {
  id: string;
  label: string;
  description: string;
};

export type CapstoneTicketDefinition = {
  ticketCode: string;
  roleSlug: string;
  nextRoleSlug: string;
  cityMissionKey: string;
  requiredLessonSlugs: readonly string[];
  passingScore: number;
  xpReward: number;
  riskOptions: readonly CapstoneOption[];
  controlOptions: readonly CapstoneOption[];
  requiredControlIds: readonly string[];
  validationOptions: readonly CapstoneOption[];
  requiredValidationIds: readonly string[];
};

export type CapstoneResponse = {
  riskLevel: string;
  controls: string[];
  validationSteps: string[];
  closureNote: string;
};

export type CapstoneScore = {
  score: number;
  passed: boolean;
  feedback: string;
  criteria: {
    risk: number;
    controls: number;
    validation: number;
    closureNote: number;
  };
};

export const capstoneTickets: readonly CapstoneTicketDefinition[] = [
  {
    ticketCode: "OSR-CC-CAP-001",
    roleSlug: "cyber-cadet",
    nextRoleSlug: "it-support-trainee",
    cityMissionKey: "open-ssh-door",
    requiredLessonSlugs: [
      "welcome-to-osiris-cyber-academy",
      "what-is-a-computer",
      "operating-systems-explained",
      "networking-fundamentals",
      "cybersecurity-fundamentals",
      "introduction-to-it-troubleshooting",
    ],
    passingScore: 100,
    xpReward: 40,
    riskOptions: [
      {
        id: "low",
        label: "Low",
        description: "Minimal exposure with little potential impact.",
      },
      {
        id: "medium",
        label: "Medium",
        description: "Meaningful weakness, but limited reach or impact.",
      },
      {
        id: "high",
        label: "High",
        description:
          "Internet exposure could lead to unauthorized server access.",
      },
      {
        id: "critical",
        label: "Critical",
        description:
          "Confirmed active compromise requiring emergency response.",
      },
    ],
    controlOptions: [
      {
        id: "restrict-nsg",
        label: "Restrict the NSG rule",
        description: "Allow SSH only from the administrator network.",
      },
      {
        id: "require-ssh-key",
        label: "Require SSH keys",
        description: "Disable password-based access to the server.",
      },
      {
        id: "enable-logging",
        label: "Enable access logging",
        description: "Send SSH access events to the SOC Police Station.",
      },
      {
        id: "leave-public-access",
        label: "Leave public SSH open",
        description:
          "Keep the existing rule so administrators can connect anywhere.",
      },
      {
        id: "disable-monitoring",
        label: "Disable monitoring",
        description: "Reduce the number of alerts generated by the server.",
      },
    ],
    requiredControlIds: ["restrict-nsg", "require-ssh-key", "enable-logging"],
    validationOptions: [
      {
        id: "test-admin-network",
        label: "Test authorized administrator access",
        description: "Confirm key-based SSH works from 10.20.30.0/24.",
      },
      {
        id: "test-public-block",
        label: "Test the public attack path",
        description: "Confirm internet-based SSH attempts are denied.",
      },
      {
        id: "verify-soc-logs",
        label: "Verify SOC logging",
        description:
          "Confirm allowed and denied access attempts appear in monitoring.",
      },
      {
        id: "skip-testing",
        label: "Close without testing",
        description: "Assume the controls work after they are saved.",
      },
    ],
    requiredValidationIds: [
      "test-admin-network",
      "test-public-block",
      "verify-soc-logs",
    ],
  },
];

export function getCapstoneByRole(roleSlug: string) {
  return capstoneTickets.find((ticket) => ticket.roleSlug === roleSlug);
}

export function getCapstoneByCode(ticketCode: string) {
  return capstoneTickets.find((ticket) => ticket.ticketCode === ticketCode);
}

function includesEvery(values: readonly string[], required: readonly string[]) {
  const valueSet = new Set(values);
  return required.every((requiredValue) => valueSet.has(requiredValue));
}

export function scoreCapstoneResponse(
  definition: CapstoneTicketDefinition,
  response: CapstoneResponse,
): CapstoneScore {
  const selectedControls = [...new Set(response.controls)];
  const selectedValidationSteps = [...new Set(response.validationSteps)];
  const allowedControlIds = new Set(
    definition.controlOptions.map((option) => option.id),
  );
  const allowedValidationIds = new Set(
    definition.validationOptions.map((option) => option.id),
  );
  const controlsAreValid = selectedControls.every((controlId) =>
    allowedControlIds.has(controlId),
  );
  const validationIsValid = selectedValidationSteps.every((stepId) =>
    allowedValidationIds.has(stepId),
  );
  const hasAllRequiredControls =
    controlsAreValid &&
    includesEvery(selectedControls, definition.requiredControlIds) &&
    selectedControls.length === definition.requiredControlIds.length;
  const hasAllValidationSteps =
    validationIsValid &&
    includesEvery(selectedValidationSteps, definition.requiredValidationIds) &&
    selectedValidationSteps.length === definition.requiredValidationIds.length;

  const normalizedNote = response.closureNote.toLowerCase();
  const noteHasAsset = /(ssh|server|payroll|access)/.test(normalizedNote);
  const noteHasOutcome = /(restrict|block|deny|close|secured)/.test(
    normalizedNote,
  );
  const noteHasMonitoring = /(log|monitor|soc|alert)/.test(normalizedNote);
  const noteIsComplete =
    response.closureNote.trim().length >= 80 &&
    noteHasAsset &&
    noteHasOutcome &&
    noteHasMonitoring;
  const noteIsDeveloping = response.closureNote.trim().length >= 50;

  const criteria = {
    risk: response.riskLevel === "high" ? 20 : 0,
    controls: hasAllRequiredControls ? 40 : 0,
    validation: hasAllValidationSteps ? 20 : 0,
    closureNote: noteIsComplete ? 20 : noteIsDeveloping ? 10 : 0,
  };
  const score = Object.values(criteria).reduce(
    (total, criterionScore) => total + criterionScore,
    0,
  );
  const passed =
    score >= definition.passingScore &&
    criteria.risk === 20 &&
    hasAllRequiredControls &&
    hasAllValidationSteps &&
    noteIsComplete;
  const feedback: string[] = [];

  if (criteria.risk === 0) {
    feedback.push(
      "Reassess the risk: internet-exposed SSH with password access is a high-risk condition, but there is no evidence of a confirmed compromise.",
    );
  }

  if (!hasAllRequiredControls) {
    feedback.push(
      "Select only the three controls that restrict the network path, strengthen authentication, and preserve access evidence.",
    );
  }

  if (!hasAllValidationSteps) {
    feedback.push(
      "Validate both outcomes: authorized administration still works, public access is blocked, and monitoring receives the events.",
    );
  }

  if (!noteIsComplete) {
    feedback.push(
      "Strengthen the closure note by naming the affected server or SSH service, the blocked/restricted outcome, and the logging or SOC verification.",
    );
  }

  if (passed) {
    feedback.push(
      "Capstone passed. Your remediation, validation plan, and closure note meet the Orientation Center standard.",
    );
  }

  return {
    score,
    passed,
    feedback: feedback.join(" "),
    criteria,
  };
}
